### ISSUE TITLE
Find position of the only set bit

### ISSUE THREAD

**Issue by Ishika2** [dsrao711/python-data-structures#59]
Hello @dsrao711,
I would like to take this issue and add a solution to the problem.

DSA Topic: BitMagic

URL: https://practice.geeksforgeeks.org/problems/find-position-of-set-bit3706/1

Reference: DSA 450 Sheet by Love Babbar

So, please assign this task to me.

Thanks and regards
Ishika Punchariya

**Comment by dsrao711** [comment]
Go ahead !
